from decimal import Decimal

data = [
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785358798")},
        "meters": [
            {
                "kwh_export": Decimal("59.6"),
                "kw1": Decimal("10071"),
                "kwh_import": Decimal("386759.8"),
                "kw3": Decimal("10724.7"),
                "kw2": Decimal("14762.2"),
                "description": "grid_meter",
                "pf_total": Decimal("1"),
                "kvar2": Decimal("-588.5"),
                "kvarh_export": Decimal("781.2"),
                "kvar3": Decimal("2158.2"),
                "kvar1": Decimal("-3494.6"),
                "kva_total": Decimal("36302.3"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("35399.8"),
                "i1": Decimal("43.5"),
                "kvar_total": Decimal("-1963.5"),
                "i2": Decimal("60.4"),
                "kva1": Decimal("10677.4"),
                "i3": Decimal("44.9"),
                "kva2": Decimal("14776.7"),
                "kva3": Decimal("10981.8"),
                "freq_hz": Decimal("49.9"),
                "pf1": Decimal("0.9"),
                "v1": Decimal("245.6"),
                "kvarh_import": Decimal("267195.1"),
                "v2": Decimal("244.8"),
                "pf3": Decimal("1"),
                "v3": Decimal("244.6"),
                "pf2": Decimal("1"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("1591.2"),
                "kwh_import": Decimal("56928.8"),
                "kw3": Decimal("1609.5"),
                "kw2": Decimal("1629.3"),
                "description": "solar_meter",
                "pf_total": Decimal("0.3"),
                "kvar2": Decimal("5763.6"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5736.8"),
                "kvar1": Decimal("5738.9"),
                "kva_total": Decimal("17908.6"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("4840.5"),
                "i1": Decimal("24.3"),
                "kvar_total": Decimal("17194.3"),
                "i2": Decimal("24.5"),
                "kva1": Decimal("5958.7"),
                "i3": Decimal("24.4"),
                "kva2": Decimal("5988.5"),
                "kva3": Decimal("5962.9"),
                "freq_hz": Decimal("49.9"),
                "pf1": Decimal("0.3"),
                "v1": Decimal("245.2"),
                "kvarh_import": Decimal("21193.2"),
                "v2": Decimal("244.9"),
                "pf3": Decimal("0.3"),
                "v3": Decimal("244.6"),
                "pf2": Decimal("0.3"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785358799094"),
    },
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785360540")},
        "meters": [
            {
                "kwh_export": Decimal("59.6"),
                "kw1": Decimal("13969.7"),
                "kwh_import": Decimal("386776.7"),
                "kw3": Decimal("11698.2"),
                "kw2": Decimal("12029.3"),
                "description": "grid_meter",
                "pf_total": Decimal("1"),
                "kvar2": Decimal("-1099.1"),
                "kvarh_export": Decimal("782.1"),
                "kvar3": Decimal("479.3"),
                "kvar1": Decimal("-3092.4"),
                "kva_total": Decimal("38027.4"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("37565.4"),
                "i1": Decimal("58.3"),
                "kvar_total": Decimal("-3803.6"),
                "i2": Decimal("49.2"),
                "kva1": Decimal("14311.5"),
                "i3": Decimal("47.9"),
                "kva2": Decimal("12077.6"),
                "kva3": Decimal("11732"),
                "freq_hz": Decimal("49.9"),
                "pf1": Decimal("1"),
                "v1": Decimal("245.5"),
                "kvarh_import": Decimal("267197.2"),
                "v2": Decimal("245.5"),
                "pf3": Decimal("1"),
                "v3": Decimal("244.9"),
                "pf2": Decimal("1"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("2389"),
                "kwh_import": Decimal("56931.6"),
                "kw3": Decimal("2436.5"),
                "kw2": Decimal("2401.2"),
                "description": "solar_meter",
                "pf_total": Decimal("0.4"),
                "kvar2": Decimal("5799.2"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5749.2"),
                "kvar1": Decimal("5731.3"),
                "kva_total": Decimal("18784.7"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("7253.8"),
                "i1": Decimal("25.3"),
                "kvar_total": Decimal("17266.3"),
                "i2": Decimal("25.6"),
                "kva1": Decimal("6213.3"),
                "i3": Decimal("25.5"),
                "kva2": Decimal("6281.8"),
                "kva3": Decimal("6248.4"),
                "freq_hz": Decimal("49.8"),
                "pf1": Decimal("0.4"),
                "v1": Decimal("245.3"),
                "kvarh_import": Decimal("21201.4"),
                "v2": Decimal("245.2"),
                "pf3": Decimal("0.4"),
                "v3": Decimal("244.9"),
                "pf2": Decimal("0.4"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785360540429"),
    },
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785362342")},
        "meters": [
            {
                "kwh_export": Decimal("59.6"),
                "kw1": Decimal("5935.5"),
                "kwh_import": Decimal("386792.9"),
                "kw3": Decimal("4588.9"),
                "kw2": Decimal("5059.3"),
                "description": "grid_meter",
                "pf_total": Decimal("0.9"),
                "kvar2": Decimal("-622.5"),
                "kvarh_export": Decimal("783.5"),
                "kvar3": Decimal("2628.8"),
                "kvar1": Decimal("-3786.3"),
                "kva_total": Decimal("17399.3"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("15395.4"),
                "i1": Decimal("28.9"),
                "kvar_total": Decimal("-1880.2"),
                "i2": Decimal("21"),
                "kva1": Decimal("7126.1"),
                "i3": Decimal("21.9"),
                "kva2": Decimal("5160.8"),
                "kva3": Decimal("5392.1"),
                "freq_hz": Decimal("50"),
                "pf1": Decimal("0.8"),
                "v1": Decimal("246.4"),
                "kvarh_import": Decimal("267198.7"),
                "v2": Decimal("245.9"),
                "pf3": Decimal("0.9"),
                "v3": Decimal("246"),
                "pf2": Decimal("1"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("6048.7"),
                "kwh_import": Decimal("56937.4"),
                "kw3": Decimal("6046.2"),
                "kw2": Decimal("6048.7"),
                "description": "solar_meter",
                "pf_total": Decimal("0.7"),
                "kvar2": Decimal("5892.8"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5937.7"),
                "kvar1": Decimal("5918.4"),
                "kva_total": Decimal("25396.4"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("18310.6"),
                "i1": Decimal("34.4"),
                "kvar_total": Decimal("17652.4"),
                "i2": Decimal("34.4"),
                "kva1": Decimal("8462"),
                "i3": Decimal("34.5"),
                "kva2": Decimal("8444.4"),
                "kva3": Decimal("8474.1"),
                "freq_hz": Decimal("49.9"),
                "pf1": Decimal("0.7"),
                "v1": Decimal("246.2"),
                "kvarh_import": Decimal("21210.2"),
                "v2": Decimal("245.6"),
                "pf3": Decimal("0.7"),
                "v3": Decimal("246"),
                "pf2": Decimal("0.7"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785362342070"),
    },
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785364143")},
        "meters": [
            {
                "kwh_export": Decimal("59.6"),
                "kw1": Decimal("4577.4"),
                "kwh_import": Decimal("386803.8"),
                "kw3": Decimal("4444.7"),
                "kw2": Decimal("4414.1"),
                "description": "grid_meter",
                "pf_total": Decimal("0.8"),
                "kvar2": Decimal("2290.7"),
                "kvarh_export": Decimal("784.1"),
                "kvar3": Decimal("3879.1"),
                "kvar1": Decimal("326"),
                "kva_total": Decimal("11523.8"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("9587.6"),
                "i1": Decimal("19.4"),
                "kvar_total": Decimal("3414.5"),
                "i2": Decimal("20.6"),
                "kva1": Decimal("4752.3"),
                "i3": Decimal("24.8"),
                "kva2": Decimal("5043"),
                "kva3": Decimal("6083.7"),
                "freq_hz": Decimal("49.9"),
                "pf1": Decimal("1"),
                "v1": Decimal("245.5"),
                "kvarh_import": Decimal("267201.6"),
                "v2": Decimal("245"),
                "pf3": Decimal("0.7"),
                "v3": Decimal("245"),
                "pf2": Decimal("0.9"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("10906.6"),
                "kwh_import": Decimal("56947.4"),
                "kw3": Decimal("10903"),
                "kw2": Decimal("10907.5"),
                "description": "solar_meter",
                "pf_total": Decimal("0.9"),
                "kvar2": Decimal("5873.3"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5926.3"),
                "kvar1": Decimal("5945.6"),
                "kva_total": Decimal("37159.4"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("32637.8"),
                "i1": Decimal("50.6"),
                "kvar_total": Decimal("17705"),
                "i2": Decimal("50.6"),
                "kva1": Decimal("12425.1"),
                "i3": Decimal("50.6"),
                "kva2": Decimal("12388.7"),
                "kva3": Decimal("12406.2"),
                "freq_hz": Decimal("49.8"),
                "pf1": Decimal("0.9"),
                "v1": Decimal("245.7"),
                "kvarh_import": Decimal("21219"),
                "v2": Decimal("244.8"),
                "pf3": Decimal("0.9"),
                "v3": Decimal("245.4"),
                "pf2": Decimal("0.9"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785364143723"),
    },
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785365945")},
        "meters": [
            {
                "kwh_export": Decimal("59.6"),
                "kw1": Decimal("9749"),
                "kwh_import": Decimal("386812.4"),
                "kw3": Decimal("10206.2"),
                "kw2": Decimal("13913.8"),
                "description": "grid_meter",
                "pf_total": Decimal("0.9"),
                "kvar2": Decimal("-831.4"),
                "kvarh_export": Decimal("785.5"),
                "kvar3": Decimal("1765.1"),
                "kvar1": Decimal("-3265.1"),
                "kva_total": Decimal("37473.8"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("36768.2"),
                "i1": Decimal("42.2"),
                "kvar_total": Decimal("592"),
                "i2": Decimal("57.2"),
                "kva1": Decimal("10339.1"),
                "i3": Decimal("42.7"),
                "kva2": Decimal("13957.8"),
                "kva3": Decimal("10424.7"),
                "freq_hz": Decimal("49.9"),
                "pf1": Decimal("0.9"),
                "v1": Decimal("244.9"),
                "kvarh_import": Decimal("267203"),
                "v2": Decimal("244.3"),
                "pf3": Decimal("1"),
                "v3": Decimal("244.3"),
                "pf2": Decimal("1"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("2867.7"),
                "kwh_import": Decimal("56959.8"),
                "kw3": Decimal("2910"),
                "kw2": Decimal("2898.2"),
                "description": "solar_meter",
                "pf_total": Decimal("0.5"),
                "kvar2": Decimal("5822.4"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5758.9"),
                "kvar1": Decimal("5789.2"),
                "kva_total": Decimal("19553.1"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("8991.3"),
                "i1": Decimal("26.3"),
                "kvar_total": Decimal("17353.1"),
                "i2": Decimal("26.6"),
                "kva1": Decimal("6452.5"),
                "i3": Decimal("26.4"),
                "kva2": Decimal("6501.1"),
                "kva3": Decimal("6446.9"),
                "freq_hz": Decimal("49.9"),
                "pf1": Decimal("0.4"),
                "v1": Decimal("245.1"),
                "kvarh_import": Decimal("21228"),
                "v2": Decimal("244.9"),
                "pf3": Decimal("0.4"),
                "v3": Decimal("244.1"),
                "pf2": Decimal("0.4"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785365945334"),
    },
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785367746")},
        "meters": [
            {
                "kwh_export": Decimal("59.6"),
                "kw1": Decimal("1551.8"),
                "kwh_import": Decimal("386818.8"),
                "kw3": Decimal("2238.5"),
                "kw2": Decimal("3291.2"),
                "description": "grid_meter",
                "pf_total": Decimal("0.6"),
                "kvar2": Decimal("510.8"),
                "kvarh_export": Decimal("786.8"),
                "kvar3": Decimal("3517.1"),
                "kvar1": Decimal("-2786.5"),
                "kva_total": Decimal("10917.7"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("7061.2"),
                "i1": Decimal("15.2"),
                "kvar_total": Decimal("1556.2"),
                "i2": Decimal("13.9"),
                "kva1": Decimal("3726.4"),
                "i3": Decimal("17.3"),
                "kva2": Decimal("3402.9"),
                "kva3": Decimal("4242"),
                "freq_hz": Decimal("49.9"),
                "pf1": Decimal("0.6"),
                "v1": Decimal("246.1"),
                "kvarh_import": Decimal("267205.2"),
                "v2": Decimal("245"),
                "pf3": Decimal("0.5"),
                "v3": Decimal("245"),
                "pf2": Decimal("1"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("10362.8"),
                "kwh_import": Decimal("56974.8"),
                "kw3": Decimal("10360.8"),
                "kw2": Decimal("10399.6"),
                "description": "solar_meter",
                "pf_total": Decimal("0.9"),
                "kvar2": Decimal("5871.4"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5864.8"),
                "kvar1": Decimal("5951.1"),
                "kva_total": Decimal("35976.4"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("31156.7"),
                "i1": Decimal("48.7"),
                "kvar_total": Decimal("17821.2"),
                "i2": Decimal("48.8"),
                "kva1": Decimal("11961.5"),
                "i3": Decimal("48.7"),
                "kva2": Decimal("11943.4"),
                "kva3": Decimal("11907.4"),
                "freq_hz": Decimal("49.9"),
                "pf1": Decimal("0.9"),
                "v1": Decimal("245.9"),
                "kvarh_import": Decimal("21236.8"),
                "v2": Decimal("244.9"),
                "pf3": Decimal("0.9"),
                "v3": Decimal("244.8"),
                "pf2": Decimal("0.9"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785367746925"),
    },
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785369548")},
        "meters": [
            {
                "kwh_export": Decimal("59.6"),
                "kw1": Decimal("1161"),
                "kwh_import": Decimal("386824.6"),
                "kw3": Decimal("757"),
                "kw2": Decimal("2289.1"),
                "description": "grid_meter",
                "pf_total": Decimal("0.3"),
                "kvar2": Decimal("995.9"),
                "kvarh_export": Decimal("787.7"),
                "kvar3": Decimal("3177.7"),
                "kvar1": Decimal("-1667.8"),
                "kva_total": Decimal("6993"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("2136.6"),
                "i1": Decimal("9.1"),
                "kvar_total": Decimal("392.1"),
                "i2": Decimal("11"),
                "kva1": Decimal("2234.2"),
                "i3": Decimal("13.7"),
                "kva2": Decimal("2689.8"),
                "kva3": Decimal("3348"),
                "freq_hz": Decimal("49.7"),
                "pf1": Decimal("0.5"),
                "v1": Decimal("244.8"),
                "kvarh_import": Decimal("267207.5"),
                "v2": Decimal("244.7"),
                "pf3": Decimal("0.2"),
                "v3": Decimal("244.4"),
                "pf2": Decimal("0.9"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("12239.5"),
                "kwh_import": Decimal("56988.9"),
                "kw3": Decimal("12261.7"),
                "kw2": Decimal("12225.1"),
                "description": "solar_meter",
                "pf_total": Decimal("0.9"),
                "kvar2": Decimal("5892.8"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5926.3"),
                "kvar1": Decimal("5861.5"),
                "kva_total": Decimal("40745.1"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("36726"),
                "i1": Decimal("55.5"),
                "kvar_total": Decimal("17812.1"),
                "i2": Decimal("55.5"),
                "kva1": Decimal("13568.1"),
                "i3": Decimal("55.7"),
                "kva2": Decimal("13578.6"),
                "kva3": Decimal("13622.4"),
                "freq_hz": Decimal("49.8"),
                "pf1": Decimal("0.9"),
                "v1": Decimal("244.6"),
                "kvarh_import": Decimal("21245.6"),
                "v2": Decimal("244.6"),
                "pf3": Decimal("0.9"),
                "v3": Decimal("244.6"),
                "pf2": Decimal("0.9"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785369548563"),
    },
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785371350")},
        "meters": [
            {
                "kwh_export": Decimal("59.7"),
                "kw1": Decimal("9982.9"),
                "kwh_import": Decimal("386837.4"),
                "kw3": Decimal("9777.1"),
                "kw2": Decimal("11303.4"),
                "description": "grid_meter",
                "pf_total": Decimal("1"),
                "kvar2": Decimal("2080.6"),
                "kvarh_export": Decimal("788.2"),
                "kvar3": Decimal("4301.4"),
                "kvar1": Decimal("-753.7"),
                "kva_total": Decimal("32358.1"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("31140.3"),
                "i1": Decimal("41.5"),
                "kvar_total": Decimal("5528.1"),
                "i2": Decimal("47.1"),
                "kva1": Decimal("10116.7"),
                "i3": Decimal("44.1"),
                "kva2": Decimal("11500.2"),
                "kva3": Decimal("10729.9"),
                "freq_hz": Decimal("50.2"),
                "pf1": Decimal("1"),
                "v1": Decimal("244"),
                "kvarh_import": Decimal("267210.8"),
                "v2": Decimal("244.1"),
                "pf3": Decimal("0.9"),
                "v3": Decimal("243.6"),
                "pf2": Decimal("1"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("3972.8"),
                "kwh_import": Decimal("56997.7"),
                "kw3": Decimal("4029.5"),
                "kw2": Decimal("3990.7"),
                "description": "solar_meter",
                "pf_total": Decimal("0.6"),
                "kvar2": Decimal("5919.6"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5869.3"),
                "kvar1": Decimal("5846.7"),
                "kva_total": Decimal("21423.5"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("12014.2"),
                "i1": Decimal("28.9"),
                "kvar_total": Decimal("17667.8"),
                "i2": Decimal("29.1"),
                "kva1": Decimal("7059.1"),
                "i3": Decimal("29.1"),
                "kva2": Decimal("7126.3"),
                "kva3": Decimal("7106.4"),
                "freq_hz": Decimal("50.3"),
                "pf1": Decimal("0.6"),
                "v1": Decimal("244.2"),
                "kvarh_import": Decimal("21254.5"),
                "v2": Decimal("244.6"),
                "pf3": Decimal("0.6"),
                "v3": Decimal("244.1"),
                "pf2": Decimal("0.6"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785371350184"),
    },
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785373151")},
        "meters": [
            {
                "kwh_export": Decimal("59.7"),
                "kw1": Decimal("15689.7"),
                "kwh_import": Decimal("386853.3"),
                "kw3": Decimal("11622.6"),
                "kw2": Decimal("9727.5"),
                "description": "grid_meter",
                "pf_total": Decimal("1"),
                "kvar2": Decimal("1257.4"),
                "kvarh_export": Decimal("789"),
                "kvar3": Decimal("3279.7"),
                "kvar1": Decimal("-1439.9"),
                "kva_total": Decimal("38560.6"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("37915.8"),
                "i1": Decimal("62.2"),
                "kvar_total": Decimal("3635.9"),
                "i2": Decimal("40.3"),
                "kva1": Decimal("15194.5"),
                "i3": Decimal("49.4"),
                "kva2": Decimal("9842.6"),
                "kva3": Decimal("12047.3"),
                "freq_hz": Decimal("50.3"),
                "pf1": Decimal("1"),
                "v1": Decimal("244.3"),
                "kvarh_import": Decimal("267213.5"),
                "v2": Decimal("244.4"),
                "pf3": Decimal("1"),
                "v3": Decimal("244"),
                "pf2": Decimal("1"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("3027.3"),
                "kwh_import": Decimal("57002.6"),
                "kw3": Decimal("3072.9"),
                "kw2": Decimal("3017.7"),
                "description": "solar_meter",
                "pf_total": Decimal("0.5"),
                "kvar2": Decimal("5860.4"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5828.7"),
                "kvar1": Decimal("5792.4"),
                "kva_total": Decimal("19747.8"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("9068.4"),
                "i1": Decimal("26.8"),
                "kvar_total": Decimal("17480.6"),
                "i2": Decimal("27"),
                "kva1": Decimal("6533.7"),
                "i3": Decimal("27"),
                "kva2": Decimal("6595.1"),
                "kva3": Decimal("6586"),
                "freq_hz": Decimal("50.3"),
                "pf1": Decimal("0.5"),
                "v1": Decimal("244.1"),
                "kvarh_import": Decimal("21263.2"),
                "v2": Decimal("244.4"),
                "pf3": Decimal("0.5"),
                "v3": Decimal("244.4"),
                "pf2": Decimal("0.5"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785373151754"),
    },
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785374953")},
        "meters": [
            {
                "kwh_export": Decimal("59.7"),
                "kw1": Decimal("11544.1"),
                "kwh_import": Decimal("386869.3"),
                "kw3": Decimal("13057.8"),
                "kw2": Decimal("12114.1"),
                "description": "grid_meter",
                "pf_total": Decimal("1"),
                "kvar2": Decimal("1058"),
                "kvarh_export": Decimal("789.8"),
                "kvar3": Decimal("3986.6"),
                "kvar1": Decimal("-1575.9"),
                "kva_total": Decimal("36120.8"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("36603.9"),
                "i1": Decimal("47.5"),
                "kvar_total": Decimal("6499.4"),
                "i2": Decimal("49.6"),
                "kva1": Decimal("11669.9"),
                "i3": Decimal("56"),
                "kva2": Decimal("12206.9"),
                "kva3": Decimal("13721"),
                "freq_hz": Decimal("50.2"),
                "pf1": Decimal("1"),
                "v1": Decimal("245.9"),
                "kvarh_import": Decimal("267216.2"),
                "v2": Decimal("246.2"),
                "pf3": Decimal("1"),
                "v3": Decimal("245.3"),
                "pf2": Decimal("1"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("2250.9"),
                "kwh_import": Decimal("57007.4"),
                "kw3": Decimal("2268.3"),
                "kw2": Decimal("2246.1"),
                "description": "solar_meter",
                "pf_total": Decimal("0.4"),
                "kvar2": Decimal("5841.7"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5850.9"),
                "kvar1": Decimal("5801"),
                "kva_total": Decimal("18725.6"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("6735.7"),
                "i1": Decimal("25.4"),
                "kvar_total": Decimal("17466.6"),
                "i2": Decimal("25.5"),
                "kva1": Decimal("6227.6"),
                "i3": Decimal("25.6"),
                "kva2": Decimal("6265.2"),
                "kva3": Decimal("6278.5"),
                "freq_hz": Decimal("50.2"),
                "pf1": Decimal("0.4"),
                "v1": Decimal("245.4"),
                "kvarh_import": Decimal("21271.9"),
                "v2": Decimal("245.6"),
                "pf3": Decimal("0.4"),
                "v3": Decimal("245.6"),
                "pf2": Decimal("0.4"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785374953341"),
    },
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785376754")},
        "meters": [
            {
                "kwh_export": Decimal("59.7"),
                "kw1": Decimal("9233.7"),
                "kwh_import": Decimal("386885.9"),
                "kw3": Decimal("12954.3"),
                "kw2": Decimal("10066.1"),
                "description": "grid_meter",
                "pf_total": Decimal("1"),
                "kvar2": Decimal("488.4"),
                "kvarh_export": Decimal("790.9"),
                "kvar3": Decimal("3742.1"),
                "kvar1": Decimal("-2304.5"),
                "kva_total": Decimal("33105.1"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("32154.4"),
                "i1": Decimal("39.2"),
                "kvar_total": Decimal("1844.8"),
                "i2": Decimal("41.2"),
                "kva1": Decimal("9567.1"),
                "i3": Decimal("56.1"),
                "kva2": Decimal("10082.4"),
                "kva3": Decimal("13651.2"),
                "freq_hz": Decimal("50"),
                "pf1": Decimal("1"),
                "v1": Decimal("244.1"),
                "kvarh_import": Decimal("267218.8"),
                "v2": Decimal("244.7"),
                "pf3": Decimal("1"),
                "v3": Decimal("243.6"),
                "pf2": Decimal("1"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("4207.8"),
                "kwh_import": Decimal("57013"),
                "kw3": Decimal("4270.5"),
                "kw2": Decimal("4238.2"),
                "description": "solar_meter",
                "pf_total": Decimal("0.6"),
                "kvar2": Decimal("5866.3"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5795.1"),
                "kvar1": Decimal("5776"),
                "kva_total": Decimal("21654.2"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("12743.4"),
                "i1": Decimal("29.3"),
                "kvar_total": Decimal("17486.5"),
                "i2": Decimal("29.6"),
                "kva1": Decimal("7153.5"),
                "i3": Decimal("29.6"),
                "kva2": Decimal("7238.4"),
                "kva3": Decimal("7202.3"),
                "freq_hz": Decimal("50.1"),
                "pf1": Decimal("0.6"),
                "v1": Decimal("244.1"),
                "kvarh_import": Decimal("21280.8"),
                "v2": Decimal("244.6"),
                "pf3": Decimal("0.6"),
                "v3": Decimal("243.6"),
                "pf2": Decimal("0.6"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785376754883"),
    },
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785378556")},
        "meters": [
            {
                "kwh_export": Decimal("59.7"),
                "kw1": Decimal("6846.4"),
                "kwh_import": Decimal("386901.2"),
                "kw3": Decimal("10061.6"),
                "kw2": Decimal("12230.9"),
                "description": "grid_meter",
                "pf_total": Decimal("1"),
                "kvar2": Decimal("-1023.2"),
                "kvarh_export": Decimal("792.3"),
                "kvar3": Decimal("2853.2"),
                "kvar1": Decimal("-4143.7"),
                "kva_total": Decimal("30928.3"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("29346.2"),
                "i1": Decimal("33"),
                "kvar_total": Decimal("-2509.7"),
                "i2": Decimal("50.4"),
                "kva1": Decimal("8107"),
                "i3": Decimal("43.2"),
                "kva2": Decimal("12354.3"),
                "kva3": Decimal("10565.8"),
                "freq_hz": Decimal("50"),
                "pf1": Decimal("0.9"),
                "v1": Decimal("246"),
                "kvarh_import": Decimal("267221.2"),
                "v2": Decimal("245.4"),
                "pf3": Decimal("1"),
                "v3": Decimal("244.7"),
                "pf2": Decimal("1"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("4043.5"),
                "kwh_import": Decimal("57020"),
                "kw3": Decimal("4059.2"),
                "kw2": Decimal("4083"),
                "description": "solar_meter",
                "pf_total": Decimal("0.6"),
                "kvar2": Decimal("5817.6"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5814.3"),
                "kvar1": Decimal("5849.1"),
                "kva_total": Decimal("21234.3"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("12141.8"),
                "i1": Decimal("29"),
                "kvar_total": Decimal("17454.7"),
                "i2": Decimal("29.1"),
                "kva1": Decimal("7116"),
                "i3": Decimal("29"),
                "kva2": Decimal("7115.5"),
                "kva3": Decimal("7093.3"),
                "freq_hz": Decimal("49.9"),
                "pf1": Decimal("0.6"),
                "v1": Decimal("245.7"),
                "kvarh_import": Decimal("21289.5"),
                "v2": Decimal("245"),
                "pf3": Decimal("0.6"),
                "v3": Decimal("244.6"),
                "pf2": Decimal("0.6"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785378556537"),
    },
    {
        "gateway": {"firmware": "m100-kundan-1.0", "gateway_id": "M100-KUNDAN-001"},
        "gateway_id": "M100-KUNDAN-001",
        "client": {
            "client_email": "payables@kundan.com.fj",
            "site_id": Decimal("1"),
            "client_name": "Kundan Singh Supermarket",
            "client_id": Decimal("4"),
        },
        "timestamp": {"ts_epoch_ms": Decimal("1785380358")},
        "meters": [
            {
                "kwh_export": Decimal("59.7"),
                "kw1": Decimal("8069.1"),
                "kwh_import": Decimal("386918.8"),
                "kw3": Decimal("8777.6"),
                "kw2": Decimal("12536.8"),
                "description": "grid_meter",
                "pf_total": Decimal("1"),
                "kvar2": Decimal("302.9"),
                "kvarh_export": Decimal("793.7"),
                "kvar3": Decimal("1935.5"),
                "kvar1": Decimal("-1840.4"),
                "kva_total": Decimal("30181"),
                "kvah_total": "m1_kvah_total",
                "kw_total": Decimal("29693.2"),
                "i1": Decimal("33.9"),
                "kvar_total": Decimal("160.6"),
                "i2": Decimal("50.7"),
                "kva1": Decimal("8299.1"),
                "i3": Decimal("36.5"),
                "kva2": Decimal("12413.7"),
                "kva3": Decimal("8921"),
                "freq_hz": Decimal("50"),
                "pf1": Decimal("1"),
                "v1": Decimal("244.9"),
                "kvarh_import": Decimal("267223.4"),
                "v2": Decimal("244.7"),
                "pf3": Decimal("1"),
                "v3": Decimal("244.8"),
                "pf2": Decimal("1"),
                "slave_id": Decimal("1"),
            },
            {
                "kwh_export": Decimal("0.3"),
                "kw1": Decimal("4287.8"),
                "kwh_import": Decimal("57024.7"),
                "kw3": Decimal("4312.8"),
                "kw2": Decimal("4311.4"),
                "description": "solar_meter",
                "pf_total": Decimal("0.6"),
                "kvar2": Decimal("5838.4"),
                "kvarh_export": Decimal("34.9"),
                "kvar3": Decimal("5827.6"),
                "kvar1": Decimal("5844.1"),
                "kva_total": Decimal("21859"),
                "kvah_total": "m2_kvah_total",
                "kw_total": Decimal("13232.9"),
                "i1": Decimal("29.5"),
                "kvar_total": Decimal("17541.6"),
                "i2": Decimal("29.6"),
                "kva1": Decimal("7224.3"),
                "i3": Decimal("29.5"),
                "kva2": Decimal("7242.8"),
                "kva3": Decimal("7228.8"),
                "freq_hz": Decimal("50"),
                "pf1": Decimal("0.6"),
                "v1": Decimal("245.2"),
                "kvarh_import": Decimal("21298.1"),
                "v2": Decimal("245"),
                "pf3": Decimal("0.6"),
                "v3": Decimal("245"),
                "pf2": Decimal("0.6"),
                "slave_id": Decimal("2"),
            },
        ],
        "ts_epoch_ms": Decimal("1785380358096"),
    },
]
