"""add remote side to user

Revision ID: 06c2f96030fa
Revises: 4cfc51614d5a
Create Date: 2026-03-21 22:08:25.382880

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "06c2f96030fa"
down_revision: Union[str, Sequence[str], None] = "4cfc51614d5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
