"""job run constraints.

Revision ID: 10e32b83e16e
Revises: 8a606e9ad4c2
Create Date: 2026-07-18 13:21:03.157386

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10e32b83e16e"
down_revision: Union[str, Sequence[str], None] = "8a606e9ad4c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_job_run_dedup"), "job_runs", type_="unique")
    op.create_index(
        "uq_job_run_dedup",
        "job_runs",
        ["reference_uid", "job_type", "reference_type", "meta", "triggered_by_uid"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_job_run_dedup",
        table_name="job_runs",
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.create_unique_constraint(
        op.f("uq_job_run_dedup"),
        "job_runs",
        ["reference_uid", "job_type", "reference_type", "meta", "triggered_by_uid"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
