"""

Revision ID: 14e545f7aa94
Revises: 54cdb2425703
Create Date: 2026-05-07 18:30:20.718470

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14e545f7aa94"
down_revision: Union[str, Sequence[str], None] = "54cdb2425703"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice_snapshots",
        sa.Column(
            "period_start_telemetry_data",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
    )
    op.add_column(
        "invoice_snapshots",
        sa.Column(
            "period_end_telemetry_data",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
    )
    op.add_column(
        "invoices",
        sa.Column(
            "period_start_telemetry_data",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
    )
    op.add_column(
        "invoices",
        sa.Column(
            "period_end_telemetry_data",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "period_end_telemetry_data")
    op.drop_column("invoices", "period_start_telemetry_data")
    op.drop_column("invoice_snapshots", "period_end_telemetry_data")
    op.drop_column("invoice_snapshots", "period_start_telemetry_data")
    # ### end Alembic commands ###
