"""add role and identity tyoe to client and user table

Revision ID: 173acbba8259
Revises: bab5b8115640
Create Date: 2026-03-20 15:42:40.622781

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "173acbba8259"
down_revision: Union[str, Sequence[str], None] = "bab5b8115640"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
