"""add invoice models

Revision ID: 1f6e08a3f6ef
Revises: 9b15e2359b50
Create Date: 2026-03-30 10:25:14.364665

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1f6e08a3f6ef"
down_revision: Union[str, Sequence[str], None] = "9b15e2359b50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
