"""

Revision ID: 202eb0999cde
Revises: bbfae97b34ff
Create Date: 2026-08-01 15:00:45.473715

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202eb0999cde"
down_revision: Union[str, Sequence[str], None] = "bbfae97b34ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_mppt_function_check",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("site_uid", sa.Uuid(), nullable=False),
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column("date_at", sa.Date(), nullable=False),
        sa.Column("from_", sa.Time(), nullable=False),
        sa.Column("to", sa.Time(), nullable=False),
        sa.Column("interval_in_minutes", sa.Integer(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_uid"],
            ["sites.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "site_uid",
            "date_at",
            "from_",
            "to",
            "interval_in_minutes",
            name="uq_site_mppt_fn_check",
        ),
        sa.UniqueConstraint("uid"),
    )
    op.create_index(
        "ix_site_mppt_fn_check_site_date",
        "site_mppt_function_check",
        ["site_uid", "date_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_mppt_function_check_site_uid"),
        "site_mppt_function_check",
        ["site_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_mppt_function_check_user_uid"),
        "site_mppt_function_check",
        ["user_uid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_site_mppt_function_check_user_uid"),
        table_name="site_mppt_function_check",
    )
    op.drop_index(
        op.f("ix_site_mppt_function_check_site_uid"),
        table_name="site_mppt_function_check",
    )
    op.drop_index("ix_site_mppt_fn_check_site_date", table_name="site_mppt_function_check")
    op.drop_table("site_mppt_function_check")
    # ### end Alembic commands ###
