"""site energy usage table

Revision ID: 28fe71a58201
Revises: bfc8c2ebba68
Create Date: 2026-08-20 13:22:58.637081

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28fe71a58201"
down_revision: Union[str, Sequence[str], None] = "bfc8c2ebba68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_energy_usage",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("site_uid", sa.Uuid(), nullable=False),
        sa.Column("date_at", sa.Date(), nullable=False),
        sa.Column("interval_in_minutes", sa.Integer(), nullable=False),
        sa.Column("telemetry_reading_str", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("energy_usage_table_str", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_uid"],
            ["sites.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("site_uid", "date_at", "interval_in_minutes", name="uq_site_energy_usage"),
        sa.UniqueConstraint("uid"),
    )
    op.create_index(
        op.f("ix_site_energy_usage_is_completed"),
        "site_energy_usage",
        ["is_completed"],
        unique=False,
    )
    op.create_index(
        "ix_site_energy_usage_site_date",
        "site_energy_usage",
        ["site_uid", "date_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_site_energy_usage_site_uid"),
        "site_energy_usage",
        ["site_uid"],
        unique=False,
    )
    op.drop_index(op.f("uq_site_create_mppt_fn_check"), table_name="site_mppt_function_check")
    op.create_unique_constraint(
        "uq_site_create_mppt_fn_check",
        "site_mppt_function_check",
        ["site_uid", "date_at", "from_", "to", "interval_in_minutes"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_site_create_mppt_fn_check", "site_mppt_function_check", type_="unique")
    op.create_index(
        op.f("uq_site_create_mppt_fn_check"),
        "site_mppt_function_check",
        ["site_uid", "date_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_site_energy_usage_site_uid"), table_name="site_energy_usage")
    op.drop_index("ix_site_energy_usage_site_date", table_name="site_energy_usage")
    op.drop_index(op.f("ix_site_energy_usage_is_completed"), table_name="site_energy_usage")
    op.drop_table("site_energy_usage")
    # ### end Alembic commands ###
