"""add tz to site table.

Revision ID: 2b7ef594cc77
Revises: 10e32b83e16e
Create Date: 2026-07-31 12:15:20.275172

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b7ef594cc77"
down_revision: Union[str, Sequence[str], None] = "10e32b83e16e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sites", sa.Column("tz", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sites", "tz")
    # ### end Alembic commands ###
