"""remove index from uid

Revision ID: 3abb29796dda
Revises: 637bd1cc486e
Create Date: 2026-04-08 10:57:11.056498

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3abb29796dda"
down_revision: Union[str, Sequence[str], None] = "637bd1cc486e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "clients", ["uid"])
    op.create_unique_constraint(None, "contract_details", ["uid"])
    op.create_unique_constraint(None, "contracts", ["uid"])
    op.drop_index(op.f("ix_devices_uid"), table_name="devices")
    op.create_unique_constraint(None, "devices", ["uid"])
    op.drop_index(op.f("ix_invoice_history_uid"), table_name="invoice_history")
    op.create_unique_constraint(None, "invoice_history", ["uid"])
    op.drop_index(op.f("ix_invoice_line_items_uid"), table_name="invoice_line_items")
    op.create_unique_constraint(None, "invoice_line_items", ["uid"])
    op.drop_index(op.f("ix_invoice_meter_data_uid"), table_name="invoice_meter_data")
    op.create_unique_constraint(None, "invoice_meter_data", ["uid"])
    op.drop_index(op.f("ix_invoices_uid"), table_name="invoices")
    op.create_unique_constraint(None, "invoices", ["uid"])
    op.create_unique_constraint(None, "sites", ["uid"])
    op.drop_index(op.f("ix_users_uid"), table_name="users")
    op.create_unique_constraint(None, "users", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.create_index(op.f("ix_users_uid"), "users", ["uid"], unique=True)
    op.drop_constraint(None, "sites", type_="unique")
    op.drop_constraint(None, "invoices", type_="unique")
    op.create_index(op.f("ix_invoices_uid"), "invoices", ["uid"], unique=True)
    op.drop_constraint(None, "invoice_meter_data", type_="unique")
    op.create_index(op.f("ix_invoice_meter_data_uid"), "invoice_meter_data", ["uid"], unique=True)
    op.drop_constraint(None, "invoice_line_items", type_="unique")
    op.create_index(op.f("ix_invoice_line_items_uid"), "invoice_line_items", ["uid"], unique=True)
    op.drop_constraint(None, "invoice_history", type_="unique")
    op.create_index(op.f("ix_invoice_history_uid"), "invoice_history", ["uid"], unique=True)
    op.drop_constraint(None, "devices", type_="unique")
    op.create_index(op.f("ix_devices_uid"), "devices", ["uid"], unique=True)
    op.drop_constraint(None, "contracts", type_="unique")
    op.drop_constraint(None, "contract_details", type_="unique")
    op.drop_constraint(None, "clients", type_="unique")
    # ### end Alembic commands ###
