"""fix weekly_billing_start_day

Revision ID: 44e2d0fd85f4
Revises: 106f1b1f8444
Create Date: 2026-05-22 13:08:43.578146

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44e2d0fd85f4"
down_revision: Union[str, Sequence[str], None] = "106f1b1f8444"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_runs",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_type", sa.Enum("COMPUTE_INVOICE", name="jobtype"), nullable=False),
        sa.Column(
            "reference_type",
            sa.Enum("CONTRACT", name="jobreferencetype"),
            nullable=False,
        ),
        sa.Column("reference_uid", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "INVALID",
                name="jobrunstatus",
            ),
            nullable=False,
        ),
        sa.Column("triggered_by_uid", sa.Uuid(), nullable=True),
        sa.Column("meta", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("result_uid", sa.Uuid(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "reference_uid",
            "job_type",
            "reference_type",
            "meta",
            "triggered_by_uid",
            name="uq_job_run_dedup",
        ),
        sa.UniqueConstraint("uid"),
    )
    op.create_index(op.f("ix_job_runs_reference_uid"), "job_runs", ["reference_uid"], unique=False)
    op.create_index(op.f("ix_job_runs_task_id"), "job_runs", ["task_id"], unique=False)
    op.add_column(
        "contract_details",
        sa.Column("weekly_billing_start_day", sa.Integer(), nullable=True),
    )
    op.alter_column(
        "contract_vat_rate_history",
        "vat_rate",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract_vat_rate_history",
        "vat_rate",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.drop_column("contract_details", "weekly_billing_start_day")
    op.drop_index(op.f("ix_job_runs_task_id"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_reference_uid"), table_name="job_runs")
    op.drop_table("job_runs")
    # ### end Alembic commands ###
