"""index device model for faster quering

Revision ID: 476214d07d16
Revises: 96fb965154f4
Create Date: 2026-04-24 09:57:29.792025

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "476214d07d16"
down_revision: Union[str, Sequence[str], None] = "96fb965154f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.create_index(op.f("ix_devices_site_uid"), "devices", ["site_uid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_devices_site_uid"), table_name="devices")
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=False)
    # ### end Alembic commands ###
