"""create users, devices, sites and clients table

Revision ID: 492d1c640ed5
Revises:
Create Date: 2026-03-20 14:42:41.847232

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "492d1c640ed5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=False),
        sa.Column("client_email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("client_id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_clients_client_email"), "clients", ["client_email"], unique=True)
    op.create_index(op.f("ix_clients_uid"), "clients", ["uid"], unique=True)
    op.create_table(
        "users",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("is_email_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_uid"), "users", ["uid"], unique=True)
    op.create_table(
        "sites",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("client_uid", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.String(length=255), nullable=False),
        sa.Column("gateway_id", sa.String(length=255), nullable=False),
        sa.Column("firmware", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_uid"],
            ["clients.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("client_uid", "site_id", name="uq_client_site"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_sites_client_uid"), "sites", ["client_uid"], unique=False)
    op.create_index(op.f("ix_sites_uid"), "sites", ["uid"], unique=True)
    op.create_table(
        "devices",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("site_uid", sa.Uuid(), nullable=False),
        sa.Column("slave_id", sa.Integer(), nullable=False),
        sa.Column("device_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_uid"],
            ["sites.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("site_uid", "slave_id", "device_type", name="uq_site_slave_device_type"),
    )
    op.create_index(op.f("ix_devices_uid"), "devices", ["uid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_devices_uid"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_sites_uid"), table_name="sites")
    op.drop_index(op.f("ix_sites_client_uid"), table_name="sites")
    op.drop_table("sites")
    op.drop_index(op.f("ix_users_uid"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_clients_uid"), table_name="clients")
    op.drop_index(op.f("ix_clients_client_email"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
