"""add unique contraint to invoice and snapshots

Revision ID: 497bc1962eb3
Revises: 14e545f7aa94
Create Date: 2026-05-12 10:04:00.817260

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "497bc1962eb3"
down_revision: Union[str, Sequence[str], None] = "14e545f7aa94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_invoice_snapshots_contract_period",
        "invoice_snapshots",
        ["contract_uid", "period_start_at", "period_end_at"],
    )
    op.create_unique_constraint(
        "uq_invoice_contract_period",
        "invoices",
        ["contract_uid", "period_start_at", "period_end_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_invoice_contract_period", "invoices", type_="unique")
    op.drop_constraint("uq_invoice_snapshots_contract_period", "invoice_snapshots", type_="unique")
    # ### end Alembic commands ###
