"""

Revision ID: 4a737a639e67
Revises: 202eb0999cde
Create Date: 2026-08-01 16:29:34.187292

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a737a639e67"
down_revision: Union[str, Sequence[str], None] = "202eb0999cde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "site_mppt_function_check",
        sa.Column("telemetry_reading_str", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "site_mppt_function_check",
        sa.Column("mppt_fn_check_table_str", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "site_mppt_function_check",
        sa.Column("is_completed", sa.Boolean(), nullable=False),
    )
    op.create_index(
        op.f("ix_site_mppt_function_check_is_completed"),
        "site_mppt_function_check",
        ["is_completed"],
        unique=False,
    )
    op.create_unique_constraint(None, "site_mppt_function_check", ["uid"])
    op.drop_column("site_mppt_function_check", "value")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "site_mppt_function_check",
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "site_mppt_function_check", type_="unique")
    op.drop_index(
        op.f("ix_site_mppt_function_check_is_completed"),
        table_name="site_mppt_function_check",
    )
    op.drop_column("site_mppt_function_check", "is_completed")
    op.drop_column("site_mppt_function_check", "mppt_fn_check_table_str")
    op.drop_column("site_mppt_function_check", "telemetry_reading_str")
    # ### end Alembic commands ###
