"""add creators uid to client and user tables.

Revision ID: 4cfc51614d5a
Revises: 61dd55068ea9
Create Date: 2026-03-21 22:05:07.881411

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cfc51614d5a"
down_revision: Union[str, Sequence[str], None] = "61dd55068ea9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("user_uid", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "clients", "users", ["user_uid"], ["uid"])
    op.add_column("users", sa.Column("registrar_uid", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "users", "users", ["registrar_uid"], ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "registrar_uid")
    op.drop_constraint(None, "clients", type_="foreignkey")
    op.drop_column("clients", "user_uid")
    # ### end Alembic commands ###
