"""add pdf_s3_key to invoices

Revision ID: 515ec6d51359
Revises: a61a1a7b7d5f
Create Date: 2026-04-26 19:51:45.606414

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "515ec6d51359"
down_revision: Union[str, Sequence[str], None] = "a61a1a7b7d5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column("pdf_s3_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "pdf_s3_key")
    # ### end Alembic commands ###
