"""add ppa on grid columns to contract.

Revision ID: 54cdb2425703
Revises: 845b38b8955a
Create Date: 2026-05-05 16:54:43.784500

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54cdb2425703"
down_revision: Union[str, Sequence[str], None] = "845b38b8955a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contract_details",
        sa.Column("with_battery", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "contract_details",
        sa.Column(
            "ppa_on_grid_no_battery_tariffs",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "contract_details",
        sa.Column("grid_meter_reading_at_commissioning_kwh", sa.Float(), nullable=True),
    )
    op.add_column(
        "contract_details",
        sa.Column("grid_meter_reading_at_commissioning_kvar", sa.Float(), nullable=True),
    )
    op.drop_column("contract_details", "grid_meter_reading_at_commissioning")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contract_details",
        sa.Column(
            "grid_meter_reading_at_commissioning",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("contract_details", "grid_meter_reading_at_commissioning_kvar")
    op.drop_column("contract_details", "grid_meter_reading_at_commissioning_kwh")
    op.drop_column("contract_details", "ppa_on_grid_no_battery_tariffs")
    op.drop_column("contract_details", "with_battery")
    # ### end Alembic commands ###
