"""convert status col to property in contract details table

Revision ID: 6040f3dec929
Revises: 1f6e08a3f6ef
Create Date: 2026-04-01 18:44:50.885066

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6040f3dec929"
down_revision: Union[str, Sequence[str], None] = "1f6e08a3f6ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contract_details", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contract_details",
        sa.Column(
            "status",
            postgresql.ENUM("DRAFT", "ACTIVE", "EXPIRED", name="contractdetailsstatus"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
