"""update user, client password column properties.

Revision ID: 61dd55068ea9
Revises: 173acbba8259
Create Date: 2026-03-21 14:48:24.502169

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61dd55068ea9"
down_revision: Union[str, Sequence[str], None] = "173acbba8259"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
