"""update contract details table.

Revision ID: 637bd1cc486e
Revises: 9ceb5900c717
Create Date: 2026-04-07 17:27:45.067388

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "637bd1cc486e"
down_revision: Union[str, Sequence[str], None] = "9ceb5900c717"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contract_details", "status")
    op.drop_column("sites", "site_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sites",
        sa.Column("site_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "contract_details",
        sa.Column(
            "status",
            postgresql.ENUM("DRAFT", "ACTIVE", "EXPIRED", name="contractdetailsstatus"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
