"""add recent_telemetry_reading to device table.

Revision ID: 64309a160c08
Revises: 4a737a639e67
Create Date: 2026-08-01 16:57:13.878674

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64309a160c08"
down_revision: Union[str, Sequence[str], None] = "4a737a639e67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column(
            "recent_telemetry_reading",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "recent_telemetry_reading")
    # ### end Alembic commands ###
