"""add meter_role and is_dual_tariff to devices

Revision ID: 79bfd3cbead4
Revises: 3fa2dbc0770d
Create Date: 2026-04-23 22:42:41.757297

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "79bfd3cbead4"
down_revision: Union[str, Sequence[str], None] = "3fa2dbc0770d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contract_settings")
    op.add_column(
        "devices",
        sa.Column("meter_role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("devices", sa.Column("is_dual_tariff", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "is_dual_tariff")
    op.drop_column("devices", "meter_role")
    op.create_table(
        "contract_settings",
        sa.Column("uid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("vat_rate", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("efl_standard_rate_kwh", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("primary_currency", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("time_format", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("date_format", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("asset_performance", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("invoice_generated", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("invoice_emailed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("updated_by_uid", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by_uid"],
            ["users.uid"],
            name=op.f("contract_settings_updated_by_uid_fkey"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("contract_settings_pkey")),
    )
    # ### end Alembic commands ###
