"""add coverage pct to contract details.

Revision ID: 7c201fd0b747
Revises: 28fe71a58201
Create Date: 2026-09-08 14:02:29.139116

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c201fd0b747"
down_revision: Union[str, Sequence[str], None] = "28fe71a58201"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contract_details", sa.Column("target_coverage_pct", sa.Float(), nullable=True))
    op.create_unique_constraint(None, "site_energy_usage", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "site_energy_usage", type_="unique")
    op.drop_column("contract_details", "target_coverage_pct")
    # ### end Alembic commands ###
