"""ba3 soc tables

Revision ID: 7eb997ec70c4
Revises: 64309a160c08
Create Date: 2026-08-14 21:22:48.658871

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7eb997ec70c4"
down_revision: Union[str, Sequence[str], None] = "64309a160c08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "battery_soc_config_history",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("site_uid", sa.Uuid(), nullable=False),
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column("config_input_str", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_uid"],
            ["sites.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.create_index(
        op.f("ix_battery_soc_config_history_site_uid"),
        "battery_soc_config_history",
        ["site_uid"],
        unique=True,
    )
    op.create_index(
        op.f("ix_battery_soc_config_history_user_uid"),
        "battery_soc_config_history",
        ["user_uid"],
        unique=False,
    )
    op.create_table(
        "battery_state_of_charge",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("site_uid", sa.Uuid(), nullable=False),
        sa.Column("battery_soc_config_uid", sa.Uuid(), nullable=False),
        sa.Column("date_at", sa.Date(), nullable=False),
        sa.Column("from_", sa.Time(), nullable=False),
        sa.Column("to", sa.Time(), nullable=False),
        sa.Column("interval_in_minutes", sa.Integer(), nullable=False),
        sa.Column("telemetry_reading_str", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("battery_soc_table_str", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["battery_soc_config_uid"],
            ["battery_soc_config_history.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["site_uid"],
            ["sites.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "site_uid",
            "date_at",
            "from_",
            "to",
            "interval_in_minutes",
            name="uq_battery_soc_check",
        ),
        sa.UniqueConstraint("uid"),
    )
    op.create_index(
        op.f("ix_battery_state_of_charge_is_completed"),
        "battery_state_of_charge",
        ["is_completed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_battery_state_of_charge_site_uid"),
        "battery_state_of_charge",
        ["site_uid"],
        unique=False,
    )
    op.create_index(
        "ix_site_battery_soc_site_date",
        "battery_state_of_charge",
        ["site_uid", "date_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_site_mppt_fn_check_site_date"), table_name="site_mppt_function_check")
    op.drop_constraint(op.f("uq_site_mppt_fn_check"), "site_mppt_function_check", type_="unique")
    op.create_index(
        "uq_site_create_mppt_fn_check",
        "site_mppt_function_check",
        ["site_uid", "date_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_site_create_mppt_fn_check", table_name="site_mppt_function_check")
    op.create_unique_constraint(
        op.f("uq_site_mppt_fn_check"),
        "site_mppt_function_check",
        ["site_uid", "date_at", "from_", "to", "interval_in_minutes"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_site_mppt_fn_check_site_date"),
        "site_mppt_function_check",
        ["site_uid", "date_at"],
        unique=False,
    )
    op.drop_index("ix_site_battery_soc_site_date", table_name="battery_state_of_charge")
    op.drop_index(
        op.f("ix_battery_state_of_charge_site_uid"),
        table_name="battery_state_of_charge",
    )
    op.drop_index(
        op.f("ix_battery_state_of_charge_is_completed"),
        table_name="battery_state_of_charge",
    )
    op.drop_table("battery_state_of_charge")
    op.drop_index(
        op.f("ix_battery_soc_config_history_user_uid"),
        table_name="battery_soc_config_history",
    )
    op.drop_index(
        op.f("ix_battery_soc_config_history_site_uid"),
        table_name="battery_soc_config_history",
    )
    op.drop_table("battery_soc_config_history")
    # ### end Alembic commands ###
