"""add first_seen_at column in sites table.

Revision ID: 845b38b8955a
Revises: 91555120607d
Create Date: 2026-05-04 16:56:38.307741

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "845b38b8955a"
down_revision: Union[str, Sequence[str], None] = "91555120607d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "contract_efl_rate_history", ["uid"])
    op.create_unique_constraint(None, "contract_vat_rate_history", ["uid"])
    op.add_column("sites", sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sites", "first_seen_at")
    op.drop_constraint(None, "contract_vat_rate_history", type_="unique")
    op.drop_constraint(None, "contract_efl_rate_history", type_="unique")
    # ### end Alembic commands ###
