"""add contract settings

Revision ID: 8650297f9d87
Revises: 79bfd3cbead4
Create Date: 2026-04-23 22:54:20.136574

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8650297f9d87"
down_revision: Union[str, Sequence[str], None] = "79bfd3cbead4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contract_settings",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("vat_rate", sa.Integer(), nullable=True),
        sa.Column("efl_standard_rate_kwh", sa.Numeric(), nullable=True),
        sa.Column("primary_currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("time_format", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date_format", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asset_performance", sa.Boolean(), nullable=False),
        sa.Column("invoice_generated", sa.Boolean(), nullable=False),
        sa.Column("invoice_emailed", sa.Boolean(), nullable=False),
        sa.Column("updated_by_uid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.add_column(
        "devices",
        sa.Column("meter_role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("devices", sa.Column("is_dual_tariff", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "is_dual_tariff")
    op.drop_column("devices", "meter_role")
    op.drop_table("contract_settings")
    # ### end Alembic commands ###
