"""remove enum from job model.

Revision ID: 8a606e9ad4c2
Revises: f41c6a6c95ff
Create Date: 2026-07-18 12:27:10.665043

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8a606e9ad4c2"
down_revision: Union[str, Sequence[str], None] = "f41c6a6c95ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "job_runs",
        "job_type",
        existing_type=postgresql.ENUM("COMPUTE_INVOICE", name="jobtype"),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "job_runs",
        "reference_type",
        existing_type=postgresql.ENUM("CONTRACT", name="jobreferencetype"),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "job_runs",
        "status",
        existing_type=postgresql.ENUM("PENDING", "RUNNING", "COMPLETED", "FAILED", "INVALID", name="jobrunstatus"),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "string_wiring", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "string_wiring", type_="unique")
    op.alter_column(
        "job_runs",
        "status",
        existing_type=sa.String(),
        type_=postgresql.ENUM("PENDING", "RUNNING", "COMPLETED", "FAILED", "INVALID", name="jobrunstatus"),
        existing_nullable=False,
    )
    op.alter_column(
        "job_runs",
        "reference_type",
        existing_type=sa.String(),
        type_=postgresql.ENUM("CONTRACT", name="jobreferencetype"),
        existing_nullable=False,
    )
    op.alter_column(
        "job_runs",
        "job_type",
        existing_type=sa.String(),
        type_=postgresql.ENUM("COMPUTE_INVOICE", name="jobtype"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
