"""refactor rate settings history table

Revision ID: 91555120607d
Revises: cd2cc46d9fb5
Create Date: 2026-05-04 09:53:32.550932

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "91555120607d"
down_revision: Union[str, Sequence[str], None] = "cd2cc46d9fb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contract_efl_rate_history",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contract_settings_uid", sa.Uuid(), nullable=False),
        sa.Column("efl_standard_rate_kwh", sa.Numeric(), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_settings_uid"],
            ["contract_settings.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.create_table(
        "contract_vat_rate_history",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contract_settings_uid", sa.Uuid(), nullable=False),
        sa.Column("vat_rate", sa.Integer(), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_settings_uid"],
            ["contract_settings.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.drop_table("contract_settings_rate_history")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contract_settings_rate_history",
        sa.Column("uid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("contract_settings_uid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("efl_standard_rate_kwh", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("vat_rate", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "effective_from",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "effective_to",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by_uid", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_settings_uid"],
            ["contract_settings.uid"],
            name=op.f("contract_settings_rate_history_contract_settings_uid_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_uid"],
            ["users.uid"],
            name=op.f("contract_settings_rate_history_created_by_uid_fkey"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("contract_settings_rate_history_pkey")),
        sa.UniqueConstraint(
            "uid",
            name=op.f("contract_settings_rate_history_uid_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("contract_vat_rate_history")
    op.drop_table("contract_efl_rate_history")
    # ### end Alembic commands ###
