"""update client and site tables.

Revision ID: 93364e944a4f
Revises: 3abb29796dda
Create Date: 2026-04-08 12:01:21.965976

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93364e944a4f"
down_revision: Union[str, Sequence[str], None] = "3abb29796dda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("clients", "client_id", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.create_unique_constraint(None, "clients", ["uid"])
    op.create_unique_constraint(None, "contract_details", ["uid"])
    op.create_unique_constraint(None, "contracts", ["uid"])
    op.create_unique_constraint(None, "devices", ["uid"])
    op.create_unique_constraint(None, "invoice_history", ["uid"])
    op.create_unique_constraint(None, "invoice_line_items", ["uid"])
    op.create_unique_constraint(None, "invoice_meter_data", ["uid"])
    op.create_unique_constraint(None, "invoices", ["uid"])
    op.add_column("sites", sa.Column("site_name", sa.String(length=255), nullable=True))
    op.alter_column("sites", "site_id", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("sites", "gateway_id", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("sites", "firmware", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.create_unique_constraint(None, "sites", ["uid"])
    op.create_unique_constraint(None, "users", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "sites", type_="unique")
    op.alter_column("sites", "firmware", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("sites", "gateway_id", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("sites", "site_id", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_column("sites", "site_name")
    op.drop_constraint(None, "invoices", type_="unique")
    op.drop_constraint(None, "invoice_meter_data", type_="unique")
    op.drop_constraint(None, "invoice_line_items", type_="unique")
    op.drop_constraint(None, "invoice_history", type_="unique")
    op.drop_constraint(None, "devices", type_="unique")
    op.drop_constraint(None, "contracts", type_="unique")
    op.drop_constraint(None, "contract_details", type_="unique")
    op.drop_constraint(None, "clients", type_="unique")
    op.alter_column("clients", "client_id", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###
