"""index client model for faster quering

Revision ID: 96fb965154f4
Revises: 8650297f9d87
Create Date: 2026-04-24 09:32:27.532640

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96fb965154f4"
down_revision: Union[str, Sequence[str], None] = "8650297f9d87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_clients_created_at",
        "clients",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("ix_clients_id", "clients", ["id"], unique=False)
    op.create_unique_constraint(None, "contract_settings", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contract_settings", type_="unique")
    op.drop_index("ix_clients_id", table_name="clients")
    op.drop_index("ix_clients_created_at", table_name="clients")
    # ### end Alembic commands ###
