"""contract ref

Revision ID: 9a73717830cb
Revises: ef051de8d162
Create Date: 2026-06-03 17:27:29.621679

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a73717830cb"
down_revision: Union[str, Sequence[str], None] = "ef051de8d162"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_contracts_contract_ref"), "contracts", ["contract_ref"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contracts_contract_ref"), table_name="contracts")
    # ### end Alembic commands ###
