"""remove site name

Revision ID: 9b15e2359b50
Revises: 06c2f96030fa
Create Date: 2026-03-29 22:22:36.563150

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9b15e2359b50"
down_revision: Union[str, Sequence[str], None] = "06c2f96030fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
