"""table updates

Revision ID: 9ceb5900c717
Revises: 6040f3dec929
Create Date: 2026-04-04 14:38:49.345178

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9ceb5900c717"
down_revision: Union[str, Sequence[str], None] = "6040f3dec929"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
