"""indexing on invoice table

Revision ID: a61a1a7b7d5f
Revises: 476214d07d16
Create Date: 2026-04-24 15:00:50.905702

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a61a1a7b7d5f"
down_revision: Union[str, Sequence[str], None] = "476214d07d16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_invoices_contract_uid", "invoices", ["contract_uid"], unique=False)
    op.create_index("ix_invoices_created_at", "invoices", [sa.literal_column("created_at DESC")], unique=False)
    op.create_index("ix_invoices_period_start_at", "invoices", ["period_start_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_invoices_period_start_at", table_name="invoices")
    op.drop_index("ix_invoices_created_at", table_name="invoices")
    op.drop_index("ix_invoices_contract_uid", table_name="invoices")
    # ### end Alembic commands ###
