"""update on contract details and invoice

Revision ID: b8761431ab83
Revises: bd5d59899552
Create Date: 2026-05-01 15:55:36.995164

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8761431ab83"
down_revision: Union[str, Sequence[str], None] = "bd5d59899552"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contract_settings_rate_history",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contract_settings_uid", sa.Uuid(), nullable=False),
        sa.Column("efl_standard_rate_kwh", sa.Numeric(), nullable=True),
        sa.Column("vat_rate", sa.Integer(), nullable=True),
        sa.Column("effective_from", sa.DateTime(), nullable=False),
        sa.Column("effective_to", sa.DateTime(), nullable=True),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_settings_uid"],
            ["contract_settings.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.add_column(
        "contract_details",
        sa.Column("efl_standard_rate_kwh", sa.Numeric(), nullable=False),
    )
    op.drop_column("contract_details", "efl_rate")
    op.drop_column("contract_settings", "vat_rate")
    op.drop_column("contract_settings", "efl_standard_rate_kwh")
    op.create_unique_constraint(None, "invoice_snapshot_line_items", ["uid"])
    op.create_unique_constraint(None, "invoice_snapshot_meter_data", ["uid"])
    op.add_column(
        "invoice_snapshots",
        sa.Column("efl_standard_rate_kwh", sa.Numeric(), nullable=False),
    )
    op.create_unique_constraint(None, "invoice_snapshots", ["uid"])
    op.add_column("invoices", sa.Column("efl_standard_rate_kwh", sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "efl_standard_rate_kwh")
    op.drop_constraint(None, "invoice_snapshots", type_="unique")
    op.drop_column("invoice_snapshots", "efl_standard_rate_kwh")
    op.drop_constraint(None, "invoice_snapshot_meter_data", type_="unique")
    op.drop_constraint(None, "invoice_snapshot_line_items", type_="unique")
    op.add_column(
        "contract_settings",
        sa.Column("efl_standard_rate_kwh", sa.NUMERIC(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "contract_settings",
        sa.Column("vat_rate", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "contract_details",
        sa.Column(
            "efl_rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("contract_details", "efl_standard_rate_kwh")
    op.drop_table("contract_settings_rate_history")
    # ### end Alembic commands ###
