"""update site mppt table name.

Revision ID: bbfae97b34ff
Revises: 2b7ef594cc77
Create Date: 2026-07-31 12:43:35.025174

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bbfae97b34ff"
down_revision: Union[str, Sequence[str], None] = "2b7ef594cc77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
