"""update tables: contract & invoice

Revision ID: bd5d59899552
Revises: 515ec6d51359
Create Date: 2026-04-30 21:14:07.872504

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd5d59899552"
down_revision: Union[str, Sequence[str], None] = "515ec6d51359"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_snapshots",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contract_uid", sa.Uuid(), nullable=False),
        sa.Column("period_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subtotal", sa.Numeric(), nullable=False),
        sa.Column("vat_rate", sa.Numeric(), nullable=False),
        sa.Column("energy_mix", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("snapshotted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_uid"],
            ["contracts.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.create_index(
        "ix_invoice_snapshots_contract_period",
        "invoice_snapshots",
        ["contract_uid", "period_start_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_snapshots_contract_uid"),
        "invoice_snapshots",
        ["contract_uid"],
        unique=False,
    )
    op.create_index(
        "ix_invoice_snapshots_snapshotted_at",
        "invoice_snapshots",
        [sa.literal_column("snapshotted_at DESC")],
        unique=False,
    )
    op.create_table(
        "invoice_snapshot_line_items",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snapshot_uid", sa.Uuid(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("energy_kwh", sa.Numeric(), nullable=True),
        sa.Column("tariff_rate", sa.Numeric(), nullable=True),
        sa.Column("tariff_period", sa.Integer(), nullable=True),
        sa.Column("tariff_slot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_uid"],
            ["invoice_snapshots.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.create_index(
        op.f("ix_invoice_snapshot_line_items_snapshot_uid"),
        "invoice_snapshot_line_items",
        ["snapshot_uid"],
        unique=False,
    )
    op.create_table(
        "invoice_snapshot_meter_data",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snapshot_uid", sa.Uuid(), nullable=False),
        sa.Column("device_uid", sa.Uuid(), nullable=True),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("period_start_reading", sa.Numeric(), nullable=False),
        sa.Column("period_end_reading", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_uid"],
            ["devices.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_uid"],
            ["invoice_snapshots.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.create_index(
        op.f("ix_invoice_snapshot_meter_data_device_uid"),
        "invoice_snapshot_meter_data",
        ["device_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_snapshot_meter_data_snapshot_uid"),
        "invoice_snapshot_meter_data",
        ["snapshot_uid"],
        unique=False,
    )
    op.add_column(
        "contract_details",
        sa.Column("actual_commissioned_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "contract_details",
        sa.Column("actual_end_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "contract_details",
        sa.Column(
            "tariff_indexed_rule_type",
            sa.String,
            server_default="EFL_LINKED",
            nullable=False,
        ),
    )
    op.add_column(
        "contract_details",
        sa.Column("grid_meter_offset_pair", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "contracts",
        sa.Column(
            "timezone",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="Pacific/Fiji",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contracts", "timezone")
    op.drop_column("contract_details", "grid_meter_offset_pair")
    op.drop_column("contract_details", "tariff_indexed_rule_type")
    op.drop_column("contract_details", "actual_end_at")
    op.drop_column("contract_details", "actual_commissioned_at")
    op.drop_index(
        op.f("ix_invoice_snapshot_meter_data_snapshot_uid"),
        table_name="invoice_snapshot_meter_data",
    )
    op.drop_index(
        op.f("ix_invoice_snapshot_meter_data_device_uid"),
        table_name="invoice_snapshot_meter_data",
    )
    op.drop_table("invoice_snapshot_meter_data")
    op.drop_index(
        op.f("ix_invoice_snapshot_line_items_snapshot_uid"),
        table_name="invoice_snapshot_line_items",
    )
    op.drop_table("invoice_snapshot_line_items")
    op.drop_index("ix_invoice_snapshots_snapshotted_at", table_name="invoice_snapshots")
    op.drop_index(op.f("ix_invoice_snapshots_contract_uid"), table_name="invoice_snapshots")
    op.drop_index("ix_invoice_snapshots_contract_period", table_name="invoice_snapshots")
    op.drop_table("invoice_snapshots")
    # ### end Alembic commands ###
