"""update ba3 soc confi history

Revision ID: bfc8c2ebba68
Revises: 7eb997ec70c4
Create Date: 2026-08-17 10:35:32.264020

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfc8c2ebba68"
down_revision: Union[str, Sequence[str], None] = "7eb997ec70c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_battery_soc_config_history_site_uid"),
        table_name="battery_soc_config_history",
    )
    op.create_index(
        op.f("ix_battery_soc_config_history_site_uid"),
        "battery_soc_config_history",
        ["site_uid"],
        unique=False,
    )
    op.create_unique_constraint(None, "battery_soc_config_history", ["uid"])
    op.create_unique_constraint(None, "battery_state_of_charge", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "battery_state_of_charge", type_="unique")
    op.drop_constraint(None, "battery_soc_config_history", type_="unique")
    op.drop_index(
        op.f("ix_battery_soc_config_history_site_uid"),
        table_name="battery_soc_config_history",
    )
    op.create_index(
        op.f("ix_battery_soc_config_history_site_uid"),
        "battery_soc_config_history",
        ["site_uid"],
        unique=True,
    )
    # ### end Alembic commands ###
