"""device last_seen_at

Revision ID: c3e8b24538a5
Revises: 9a73717830cb
Create Date: 2026-06-16 17:43:11.295642

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3e8b24538a5"
down_revision: Union[str, Sequence[str], None] = "9a73717830cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("devices", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "last_seen_at")
    # ### end Alembic commands ###
