"""make index rule optional in contract details table

Revision ID: cd2cc46d9fb5
Revises: 39a25cf7081f
Create Date: 2026-05-03 21:50:59.779149

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd2cc46d9fb5"
down_revision: Union[str, Sequence[str], None] = "39a25cf7081f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract_details",
        "tariff_indexed_rule_type",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'EFL_LINKED'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract_details",
        "tariff_indexed_rule_type",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'EFL_LINKED'::character varying"),
    )
    # ### end Alembic commands ###
