"""make updated_by_uid optional

Revision ID: d940046bbe13
Revises: 71de9d946429
Create Date: 2026-04-21 11:02:08.299738

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d940046bbe13"
down_revision: Union[str, Sequence[str], None] = "71de9d946429"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contract_settings")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contract_settings",
        sa.Column("uid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("vat_rate", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("efl_standard_rate_kwh", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("primary_currency", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("time_format", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("date_format", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("asset_perfomance", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("invoice_generated", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("invoice_emailed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("updated_by_uid", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["updated_by_uid"],
            ["users.uid"],
            name=op.f("contract_settings_updated_by_uid_fkey"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("contract_settings_pkey")),
    )
    # ### end Alembic commands ###
