"""add comissioning date to pv summary

Revision ID: e38dcf7d9309
Revises: f76756ba4730
Create Date: 2026-07-10 17:22:31.739035

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e38dcf7d9309"
down_revision: Union[str, Sequence[str], None] = "f76756ba4730"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "panel_reference", ["uid"])
    op.add_column(
        "pv_summary",
        sa.Column("commissioned_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_unique_constraint(None, "pv_summary", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pv_summary", type_="unique")
    op.drop_column("pv_summary", "commissioned_at")
    op.drop_constraint(None, "panel_reference", type_="unique")
    # ### end Alembic commands ###
