"""make rate-history nullable

Revision ID: ecd86439d93e
Revises: b8761431ab83
Create Date: 2026-05-01 16:14:27.934475

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecd86439d93e"
down_revision: Union[str, Sequence[str], None] = "b8761431ab83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "contract_settings_rate_history", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contract_settings_rate_history", type_="unique")
    # ### end Alembic commands ###
