"""add id to job run table

Revision ID: ef051de8d162
Revises: 6635c03f6f51
Create Date: 2026-05-22 22:20:18.821055

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef051de8d162"
down_revision: Union[str, Sequence[str], None] = "6635c03f6f51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_runs",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
    )
    op.create_unique_constraint(None, "job_runs", ["uid"])
    op.create_unique_constraint(None, "job_runs", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "job_runs", type_="unique")
    op.drop_constraint(None, "job_runs", type_="unique")
    op.drop_column("job_runs", "id")
    # ### end Alembic commands ###
