"""string wiring table

Revision ID: f41c6a6c95ff
Revises: 27b61f9eb5e7
Create Date: 2026-07-13 10:40:56.459520

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f41c6a6c95ff"
down_revision: Union[str, Sequence[str], None] = "27b61f9eb5e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "string_wiring",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("site_uid", sa.Uuid(), nullable=False),
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column("string_input", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("wring_schematics", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mppt_fn_table", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("expected_mppt_a_table", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_uid"],
            ["sites.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.create_index(op.f("ix_string_wiring_site_uid"), "string_wiring", ["site_uid"], unique=True)
    op.create_index(op.f("ix_string_wiring_user_uid"), "string_wiring", ["user_uid"], unique=False)
    op.create_unique_constraint(None, "pv_degradation", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pv_degradation", type_="unique")
    op.drop_index(op.f("ix_string_wiring_user_uid"), table_name="string_wiring")
    op.drop_index(op.f("ix_string_wiring_site_uid"), table_name="string_wiring")
    op.drop_table("string_wiring")
    # ### end Alembic commands ###
