"""add site configs tables

Revision ID: f76756ba4730
Revises: c3e8b24538a5
Create Date: 2026-07-10 13:22:32.937560

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f76756ba4730"
down_revision: Union[str, Sequence[str], None] = "c3e8b24538a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "panel_reference",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("site_uid", sa.Uuid(), nullable=False),
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column("panel_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("watt", sa.Float(), nullable=False),
        sa.Column("vmp", sa.Float(), nullable=False),
        sa.Column("voc", sa.Float(), nullable=False),
        sa.Column("imp", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_uid"],
            ["sites.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.create_index(
        op.f("ix_panel_reference_site_uid"),
        "panel_reference",
        ["site_uid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_panel_reference_user_uid"),
        "panel_reference",
        ["user_uid"],
        unique=False,
    )
    op.create_table(
        "pv_summary",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("site_uid", sa.Uuid(), nullable=False),
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column("expected_production_kwh", sa.Numeric(), nullable=False),
        sa.Column("system_size_kwp", sa.Numeric(), nullable=False),
        sa.Column("year1_degradation", sa.Float(), nullable=False),
        sa.Column("year2plus_degradation", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_uid"],
            ["sites.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("uid"),
    )
    op.create_index(op.f("ix_pv_summary_site_uid"), "pv_summary", ["site_uid"], unique=True)
    op.create_index(op.f("ix_pv_summary_user_uid"), "pv_summary", ["user_uid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pv_summary_user_uid"), table_name="pv_summary")
    op.drop_index(op.f("ix_pv_summary_site_uid"), table_name="pv_summary")
    op.drop_table("pv_summary")
    op.drop_index(op.f("ix_panel_reference_user_uid"), table_name="panel_reference")
    op.drop_index(op.f("ix_panel_reference_site_uid"), table_name="panel_reference")
    op.drop_table("panel_reference")
    # ### end Alembic commands ###
