class Constants:
    BLOCKLIST_PREFIX = "blocked:key"
    CLIENT_SITES = "sites:client:uid"
    SITE_STATS_STREAM = "site_stats:stream:uid"
    SITE_STAT = "site_stat:uid"
    ENERGY_PORTFOLIO = "ep:m:y"
    MPPT_FN_CHECK = "mppt_fn_check:site_uid:date_at"
    BA3_SOC = "ba3_soc:site_uid:date_at"
    MPPT_BA3_SOC_LOCK = "mppt_ba3_soc:lock:site_uid:date_at"
    SITE_ENERGY_USAGE = "site_energy_usage:site_uid:date_at"
    SITE_ENERGY_USAGE_LOCK = "site_energy_usage:lock:site_uid:date_at"
